version: 0.2    
phases:
    install:
        runtime-versions:
            dotnet: 8.0

  build:
    commands:
      - dotnet --version  # Check the correct SDK version
      - dotnet restore JackOfAllCodes.sln
      - dotnet build JackOfAllCodes.sln
