version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0  # Use .NET 8 runtime
    commands:
      - echo Installing dependencies...
      - dotnet restore JackOfAllCodes.Web/JackOfAllCodes.Web.csproj
      - dotnet restore JackOfAllCodes.UnitTests/JackOfAllCodes.UnitTests.csproj  # Restore unit test dependencies

  build:
    commands:
      - echo Building the .NET project...
      - dotnet build JackOfAllCodes.Web/JackOfAllCodes.Web.csproj --configuration Release
      - echo Building unit tests...
      - dotnet build JackOfAllCodes.UnitTests/JackOfAllCodes.UnitTests.csproj --configuration Release  # Build unit tests project
      - echo Running unit tests...
      - dotnet test JackOfAllCodes.UnitTests/JackOfAllCodes.UnitTests.csproj --configuration Release --no-build --logger "trx;LogFileName=test_results.trx"  # Generate test results in trx format

  post_build:
    commands:
      - echo Publishing the .NET project...
      - dotnet publish JackOfAllCodes.Web/JackOfAllCodes.Web.csproj --configuration Release --output ./output
      - echo Preparing artifact...
      - cp appspec.yml ./output/
      - cp -r scripts/ ./output/
      - cp src/JackOfAllCodes.UnitTests/TestResults/test_results.trx ./output/  # Copy .trx file to output directory

artifacts:
  files:
    - ./output/**/*.*  # Include all files from the output directory
  discard-paths: no

reports:
  test-reports:
    files:
      - './output/test_results.trx'  # Ensure this matches the actual path of the .trx file in the output directory
    name: JackOfAllCodes.UnitTestsResults  # The name of the test report
