version: 0.2    
phases:
  install:
    commands:
      - curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 8.0 
  build:
    commands:
      - dotnet restore JackOfAllCodes.sln
      - dotnet build JackOfAllCodes.sln