version: 0.2    
phases:
  install:
    commands:
      # Uninstall .NET 6
      - sudo apt-get remove --purge dotnet-sdk-6.0 || true
      - sudo apt-get autoremove || true

      # Install .NET 8 to a specific directory
      - curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 8.0 --install-dir /root/.dotnet

      # Add the installed .NET 8 SDK to the path
      - export PATH=/root/.dotnet:/root/.dotnet/tools:$PATH

      # Verify the installed .NET version
      - dotnet --version

  build:
    commands:
      # Restore and build using the correct SDK
      - dotnet restore JackOfAllCodes.sln
      - dotnet build JackOfAllCodes.sln
