version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0  # Use .NET 8 runtime
    commands:
      - echo Installing dependencies...
      - dotnet restore JackOfAllCodes.Web/JackOfAllCodes.Web.csproj
  build:
    commands:
      - echo Building the .NET project...
      - dotnet build JackOfAllCodes.Web/JackOfAllCodes.Web.csproj --configuration Release
      - echo Publishing the .NET project...
      - dotnet publish JackOfAllCodes.Web/JackOfAllCodes.Web.csproj --configuration Release --output ./output
  post_build:
    commands:
      - echo Preparing artifact...
      - cp appspec.yml ./output/
      - cp -r scripts/ ./output/
artifacts:
  files:
    - ./output/**/*
  discard-paths: yes

