version: 0.2    
phases:
  install:
    commands:
      # Install .NET 8 to a specific directory
      - curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 8.0 --install-dir /root/.dotnet

      # Set DOTNET_ROOT to the installation directory to ensure all dotnet commands use .NET 8
      - export DOTNET_ROOT=/root/.dotnet

      # Add the .NET installation directory to the PATH
      - export PATH=/root/.dotnet:/root/.dotnet/tools:$PATH
      
      # Verify the installed .NET SDK version
      - dotnet --version

  build:
    commands:
      # Restore and build using the correct SDK
      - dotnet restore JackOfAllCodes.sln
      - dotnet build JackOfAllCodes.sln
